#!/bin/sh -e

die() {
	echo >&2 "$0: [error]" "$@"
	exit 1
}

quit() {
	echo >&2 "$@"
	exit 0
}

# get version
VER="$(curl -sLf 'https://golang.org/VERSION?m=text')" \
|| die 'Cannot contact golang.org to get the latest Go version.'

VER="$(echo "$VER" | grep ^go)"

# check current version, if installed
[ -n "$(which go)" ]	\
&& [ "$VER" = "$(go version | cut -d ' ' -f 3)" ]	\
&& quit "Current Go version ${VER#go} is the latest."

echo "Found new Go version ${VER#go}, downloading..."

# working directory
WD="$(mktemp -d)"

# shellcheck disable=SC2064
trap "rm -rf $WD" EXIT
# shellcheck disable=SC2064
trap "echo >&2 '$0: interrupted!'" INT TERM QUIT HUP

# download
ARCHIVE="$VER.linux-amd64.tar.gz"
URL="https://go.dev/dl/$ARCHIVE"

curl -sLf -o "$WD/$ARCHIVE" "$URL" || die "Cannot download Go from $URL"

# remove any previous installation
echo "Installing (requires sudo)..."

INSTALL_DIR=/usr/local

[ -d "$INSTALL_DIR/go" ] && sudo rm -rf "$INSTALL_DIR/go"

# extract archive
sudo tar -C "$INSTALL_DIR" -xzf "$WD/$ARCHIVE"

GO="$INSTALL_DIR/go/bin/go"

# make sure telemetry is off
"$GO" telemetry off

# install tools
echo "Updating Go tools..."
"$GO" install golang.org/x/tools/cmd/goimports@latest
"$GO" install golang.org/x/tools/gopls@latest
"$GO" install golang.org/x/tools/cmd/deadcode@latest
"$GO" install honnef.co/go/tools/cmd/staticcheck@latest

echo "Installation complete."
